version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ccm_registry
      POSTGRES_USER: ccm_user
      POSTGRES_PASSWORD: ccm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccm_user -d ccm_registry"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://ccm_user:ccm_password@postgres:5432/ccm_registry
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRY: 7d
      CORS_ORIGIN: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json
      - ./api/tsconfig.json:/app/tsconfig.json
    command: npm run dev

volumes:
  postgres_data: